default: &default
  adapter: postgresql
  database: centro_medico_maracay_gineco-obstetra_development
  username: postgres
  password:
  host: localhost
  encoding: utf8

development:
  <<: *default

test:
  <<: *default
  database: centro_medico_maracay_gineco-obstetra_test
  
production:
  <<: *default
  database: centro_medico_maracay_gineco-obstetra_production
  username: centro_medico_maracay_gineco-obstetra
  password: <%= ENV['CENTRO_MEDICO_MARACAY_GINECO-OBSTETRA_DATABASE_PASSWORD'] %>
